// Shared utilities for all phase scripts.
// Keep this small — only what 2+ phases need.

const fs = require('fs');
const path = require('path');
const { URL } = require('url');

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(ROOT, 'output');
const ARTIFACTS = path.join(OUTPUT, 'artifacts');
const AUTH_DIR = path.join(OUTPUT, 'auth');
const STORAGE_DIR = path.join(OUTPUT, 'storage');
const REPORTS_DIR = path.join(OUTPUT, 'reports');
const LOGS_DIR = path.join(OUTPUT, 'logs');

for (const d of [OUTPUT, ARTIFACTS, AUTH_DIR, STORAGE_DIR, REPORTS_DIR, LOGS_DIR]) {
  fs.mkdirSync(d, { recursive: true });
}

// Config resolution order:
//   1. --target <url> or TARGET_URL env var — if config.json is missing, auto-generates it.
//   2. config.json on disk — used as-is.
//   3. Neither — throw.
// Auto-generation writes a minimal config once so every child phase process reads
// the same target without needing --target threaded through spawnSync.
function loadConfig() {
  const configPath = path.join(ROOT, 'config.json');
  const argv = process.argv;
  const tIdx = argv.findIndex(a => a === '--target' || a.startsWith('--target='));
  const cliTarget = tIdx >= 0
    ? (argv[tIdx].includes('=') ? argv[tIdx].split('=')[1] : argv[tIdx + 1])
    : process.env.TARGET_URL;

  let cfg;
  const configExists = fs.existsSync(configPath);

  if (configExists) {
    cfg = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    if (cliTarget) cfg.target = cliTarget; // CLI override (doesn't rewrite file)
  } else if (cliTarget) {
    // Auto-generate minimal config and persist it
    cfg = {
      target: cliTarget,
      outputDir: './output',
      mode: 'full',
      scope: { domains: [cliTarget], avoid: [] },
      limits: {
        maxCrawlPages: 40,
        maxCrawlDepth: 5,
        fuzzConcurrency: 4,
        requestTimeoutMs: 15000,
        fuzzJitterMs: 100,
      },
      reportFormats: ['json', 'md'],
      _autoGenerated: true,
    };
    fs.writeFileSync(configPath, JSON.stringify(cfg, null, 2));
  } else {
    throw new Error('No target — provide one via config.json, --target <url>, or TARGET_URL env var.');
  }

  // Backfill scope if an existing config.json lacks it
  if (!cfg.scope?.domains || cfg.scope.domains.length === 0) {
    cfg.scope = cfg.scope || {};
    cfg.scope.domains = [cfg.target];
    cfg.scope.avoid = cfg.scope.avoid || [];
  }
  return cfg;
}

function loadCredentials() {
  const credPath = path.join(ROOT, 'credentials.json');
  if (!fs.existsSync(credPath)) return { roles: [] };
  return JSON.parse(fs.readFileSync(credPath, 'utf8'));
}

function writeArtifact(name, data) {
  const p = path.join(ARTIFACTS, name);
  fs.writeFileSync(p, JSON.stringify(data, null, 2));
  return p;
}

function readArtifact(name) {
  const p = path.join(ARTIFACTS, name);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

// Fetch with an actual working timeout (Node's fetch doesn't accept {timeout}).
async function fetchWithTimeout(url, opts = {}, timeoutMs = 15000) {
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...opts, signal: controller.signal });
    return res;
  } finally {
    clearTimeout(t);
  }
}

// Canonicalize an endpoint path for deduplication.
// "/users/123" and "/users/456" both become "/users/:id".
function canonicalizePath(urlOrPath) {
  let p;
  try {
    p = new URL(urlOrPath).pathname;
  } catch {
    p = urlOrPath.split('?')[0];
  }
  // Collapse trailing slash (but keep root)
  if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
  // Replace numeric segments with :id
  p = p.replace(/\/\d+(?=\/|$)/g, '/:id');
  // Replace UUIDs
  p = p.replace(/\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, '/:uuid');
  // Replace hex-looking ids of length >= 24 (mongo etc.)
  p = p.replace(/\/[0-9a-f]{24,}(?=\/|$)/gi, '/:hexid');
  return p;
}

function isSameOrigin(targetUrl, candidate) {
  try {
    const a = new URL(targetUrl);
    const b = new URL(candidate, targetUrl);
    return a.origin === b.origin;
  } catch { return false; }
}

// In-scope check honors config.scope.domains (multi-domain).
// If config.scope.domains is missing, falls back to target-origin only.
function isInScope(cfg, candidateUrl) {
  try {
    const b = new URL(candidateUrl, cfg.target);
    const domains = cfg.scope?.domains && cfg.scope.domains.length
      ? cfg.scope.domains
      : [cfg.target];
    return domains.some(d => {
      try { return new URL(d).origin === b.origin; } catch { return false; }
    });
  } catch { return false; }
}

// Avoid check — returns reason if matched, null if allowed.
function avoidReason(cfg, candidateUrlOrPath) {
  const rules = cfg.scope?.avoid || [];
  if (rules.length === 0) return null;
  let p;
  try { p = new URL(candidateUrlOrPath, cfg.target).pathname; }
  catch { p = String(candidateUrlOrPath).split('?')[0]; }
  for (const r of rules) {
    if (r.type === 'path') {
      if (r.pattern && (p === r.pattern || p.startsWith(r.pattern))) return r.reason || 'avoid rule';
    } else if (r.type === 'regex') {
      try { if (new RegExp(r.pattern).test(p)) return r.reason || 'avoid regex rule'; } catch {}
    }
  }
  return null;
}

function log(phase, msg) {
  const line = `[${new Date().toISOString()}] [phase${phase}] ${msg}\n`;
  process.stdout.write(line);
  fs.appendFileSync(path.join(LOGS_DIR, 'orchestrator.log'), line);
}

module.exports = {
  ROOT, OUTPUT, ARTIFACTS, AUTH_DIR, STORAGE_DIR, REPORTS_DIR, LOGS_DIR,
  loadConfig, loadCredentials,
  writeArtifact, readArtifact,
  fetchWithTimeout,
  canonicalizePath, isSameOrigin, isInScope, avoidReason,
  log,
};
