// Phase 6: Session Setup & Auth Profiling
// One Playwright context per role. Auto-generates a refresh script per role.

const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const {
  loadConfig, loadCredentials, writeArtifact, log,
  AUTH_DIR,
} = require('./lib');

async function attemptLogin(browser, target, role) {
  const context = await browser.newContext({ ignoreHTTPSErrors: true });
  const page = await context.newPage();

  const xhrCalls = [];
  const authHeaders = new Set();
  context.on('request', req => {
    if (['xhr', 'fetch'].includes(req.resourceType())) {
      xhrCalls.push({ url: req.url(), method: req.method() });
      const auth = req.headers().authorization;
      if (auth) authHeaders.add(auth.split(' ')[0]); // "Bearer", "Basic", etc.
    }
  });

  const loginUrl = role.loginUrl || target;
  await page.goto(loginUrl, { waitUntil: 'domcontentloaded', timeout: 30000 });

  // Try to find username + password inputs heuristically
  const userSel = role.selectors?.username
    || 'input[type="email"], input[name*="user" i], input[name*="email" i], input[id*="user" i], input[id*="email" i]';
  const passSel = role.selectors?.password
    || 'input[type="password"]';
  const submitSel = role.selectors?.submit
    || 'button[type="submit"], input[type="submit"], button:has-text("Log in"), button:has-text("Login"), button:has-text("Sign in")';

  try {
    await page.waitForSelector(userSel, { timeout: 10000 });
    await page.fill(userSel, role.username);
    await page.fill(passSel, role.password);
    await Promise.all([
      page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {}),
      page.click(submitSel),
    ]);
  } catch (err) {
    await context.close();
    return { role: role.name, success: false, error: `login form interaction failed: ${err.message}` };
  }

  const cookies = await context.cookies();
  const storageState = await context.storageState();
  const localStorage = await page.evaluate(() => ({ ...localStorage })).catch(() => ({}));
  const sessionStorage = await page.evaluate(() => ({ ...sessionStorage })).catch(() => ({}));

  // Detect auth mechanism
  let authMechanism = 'session-cookie';
  const token = localStorage.token || localStorage.authToken || sessionStorage.token || null;
  if (token) {
    authMechanism = token.startsWith('eyJ') ? 'jwt-localStorage' : 'token-localStorage';
  } else if (authHeaders.has('Bearer')) {
    authMechanism = 'jwt-bearer';
  } else if (authHeaders.has('Basic')) {
    authMechanism = 'http-basic';
  }

  // Save storageState — full reuse file
  const stateFile = path.join(AUTH_DIR, `state-${role.name}.json`);
  fs.writeFileSync(stateFile, JSON.stringify(storageState, null, 2));

  // Generate a refresh script for this role.
  const refreshScript = `// Auto-generated by phase6-auth.js for role="${role.name}"
// Replays login and rewrites state-${role.name}.json. Run with: node refresh-${role.name}.js
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext();
  const page = await ctx.newPage();
  await page.goto(${JSON.stringify(loginUrl)}, { waitUntil: 'domcontentloaded' });
  await page.fill(${JSON.stringify(userSel)}, ${JSON.stringify(role.username)});
  await page.fill(${JSON.stringify(passSel)}, ${JSON.stringify(role.password)});
  await Promise.all([
    page.waitForLoadState('networkidle').catch(() => {}),
    page.click(${JSON.stringify(submitSel)}),
  ]);
  const state = await ctx.storageState();
  fs.writeFileSync(path.join(__dirname, 'state-${role.name}.json'), JSON.stringify(state, null, 2));
  await browser.close();
  console.log('refreshed');
})().catch(e => { console.error(e); process.exit(1); });
`;
  fs.writeFileSync(path.join(AUTH_DIR, `refresh-${role.name}.js`), refreshScript);

  await context.close();

  return {
    role: role.name,
    success: true,
    loginUrl,
    authMechanism,
    hasToken: !!token,
    cookies: cookies.map(c => ({ name: c.name, domain: c.domain, path: c.path, httpOnly: c.httpOnly })),
    stateFile: `state-${role.name}.json`,
    refreshScript: `refresh-${role.name}.js`,
    xhrCallsSeen: xhrCalls.length,
  };
}

(async () => {
  const cfg = loadConfig();
  const creds = loadCredentials();
  const rolesCfg = creds.roles || [];

  const result = {
    phase: 6,
    timestamp: new Date().toISOString(),
    roles: [],
    unauthenticated: true,
  };

  if (rolesCfg.length === 0) {
    log(6, `no credentials — proceeding unauthenticated only`);
    writeArtifact('phase6_auth.json', result);
    return;
  }

  const browser = await chromium.launch({ headless: true });
  try {
    for (const r of rolesCfg) {
      log(6, `attempting login for role=${r.name}`);
      const profile = await attemptLogin(browser, cfg.target, r);
      result.roles.push(profile);
      log(6, `  → ${r.name}: ${profile.success ? 'OK' : 'FAIL: ' + profile.error}`);
    }
    // Validate: at least one role succeeded
    const anySucceeded = result.roles.some(r => r.success);
    if (!anySucceeded) {
      log(6, `WARN: no role authenticated — continuing unauthenticated only`);
    }
  } finally {
    await browser.close();
  }

  writeArtifact('phase6_auth.json', result);
  log(6, `OK: ${result.roles.filter(r => r.success).length}/${result.roles.length} roles authenticated`);
})();
